name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure test deps are present even if not in requirements.txt
          pip install --upgrade --quiet pytest pandas pandera jsonschema

      - name: Run tests
        env:
          PYTHONPATH: .
          DISABLE_PANDERA_IMPORT_WARNING: "True"
        run: pytest -q
