name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure pytest exists even if not in requirements
          python - <<'PY'
          import pkgutil, sys
          sys.exit(0 if pkgutil.find_loader("pytest") else 1)
          PY
        continue-on-error: true
      - name: Fallback: install test deps if missing
        if: ${{ failure() }}
        run: pip install pytest

      - name: Run tests
        env:
          PYTHONPATH: .
        run: pytest -q
