name: cross-platform-smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  smoke:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install project
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -e .[dev] || pip install -e .

      - name: Smoke import + versions
        run: |
          python -c "import sys; print(sys.version)"
          python -c "import fairy; print('fairy import OK')"

      - name: Pytest smoke
        run: |
          pytest -q || pytest -q -k "roundtrip or report or golden"
